Traceback (most recent call last):
  File "/home/dikshan/Desktop/Python_automation/module6/linux_cmds/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate error to STDERR")
ValueError: Now we generate error to STDERR
